
GET http://localhost:4000/comments HTTP/1.1

###

POST http://localhost:4000/comments HTTP/1.1
content-type: application/json

{
    "author": "Michal",
    "content": "check2" 
}


############################ PROJECTS ##############################


# GET SPECIFIC PROJECT FROM TEAM
GET http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312ffa73acc426af9fe0bf HTTP/1.1 

###

# CREATE NEW PROJECT IN TEAM
POST http://localhost:4000/teams/602daad612d3182dc04f8050/projects HTTP/1.1
content-type: application/json

{
    "projectName": "nowy testowy projekt",
    "owner": {
        "id": "602e41a034644bbf940bea0b",
        "name": "Michauuu"
    }
}

###


# UPDATE MEMBERS IN PROJECT
PUT http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312464300a9f211f95c8f8/members HTTP/1.1

content-type: application/json

{
    "members": []
}

###

# UPDATE PROJECT STATUS
PUT http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312464300a9f211f95c8f8/status HTTP/1.1
content-type: application/json

{
    "status": "Done",
    "name": "nowa name"
}


###

# DELETE PROJECT 
DELETE http://localhost:4000/teams/602faee3cc18aa0b4d0d974b/projects/60310726d9b3e01ea2566110 HTTP/1.1


#################################### NOTES ##############################################

# GET ALL NOTES FROM PROJECT
GET http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312ffa73acc426af9fe0bf/notes HTTP/1.1

###

# CREATE NEW NOTE
POST http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312ffa73acc426af9fe0bf/notes HTTP/1.1
Content-Type: application/json

{
    "name": "Test Note",
    "author": {"name": "Michal", "id": "602e41a034644bbf940bea0b"}
}

###

# UPDATE NOTE
PUT http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312ffa73acc426af9fe0bf/notes/603133d3bd68ce281747ac30 HTTP/1.1
Content-Type: application/json

{
    "content": "updated contentasdwegsdgfg"
}

###

# DELETE NOTE
DELETE http://localhost:4000/teams/602daad612d3182dc04f8050/projects/60312ffa73acc426af9fe0bf/notes/603133d3bd68ce281747ac30 HTTP/1.1

