
GET http://localhost:4000/comments HTTP/1.1

###

POST http://localhost:4000/comments HTTP/1.1
content-type: application/json

{
    "author": "Michal",
    "content": "check2" 
}

###
# ____________________________ Authentication ____________________________

###
# login
POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
    "email": "olek@mail.com",
    "password": "123456"
}

###
# ____________________________ USERS ____________________________
 
###
# get users
GET http://localhost:3000/users HTTP/1.1


###
# get user
GET http://localhost:3000/users/60322728bc2c56019096b218 HTTP/1.1


###
# get me
GET http://localhost:3000/users/me HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcyOGJjMmM1NjAxOTA5NmIyMTgiLCJpYXQiOjE2MTM4OTk2MTB9.o0jJa82-vmzRIJMrjBJovUB1qcXfetO-cf12WNNwWt4

###
# confirm user
GET http://localhost:3000/users/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcxZGJjMmM1NjAxOTA5NmIyMTciLCJpYXQiOjE2MTM5MDc2MzF9.c-rfYIqw-jXZL9834jtusjtSpQq5yeHWXZ_73aQdxX4 HTTP/1.1

###
# create users
POST http://localhost:3000/users/create HTTP/1.1
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@mail.com",
    "password": "12345"
}

###
# send email
POST http://localhost:3000/users/email HTTP/1.1
Content-Type: application/json

{
    "email": "zdvmdstrjlmkestgjr@mhzayt.online",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcxZGJjMmM1NjAxOTA5NmIyMTciLCJpYXQiOjE2MTM5MDc2MzF9.c-rfYIqw-jXZL9834jtusjtSpQq5yeHWXZ_73aQdxX4"
}

###
# add project
POST http://localhost:3000/users/project HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcxZGJjMmM1NjAxOTA5NmIyMTciLCJpYXQiOjE2MTM5MDc2MzF9.c-rfYIqw-jXZL9834jtusjtSpQq5yeHWXZ_73aQdxX4
Content-Type: application/json

{
    "projectId": "60321601a0356b0924c94bde"
}

###
# change name
PUT http://localhost:3000/users/name HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcxZGJjMmM1NjAxOTA5NmIyMTciLCJpYXQiOjE2MTM5MDc2MzF9.c-rfYIqw-jXZL9834jtusjtSpQq5yeHWXZ_73aQdxX4
Content-Type: application/json

{
    "name": "Aleksander"
}

###
# change password
PUT http://localhost:3000/users/password HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcxZGJjMmM1NjAxOTA5NmIyMTciLCJpYXQiOjE2MTM5MDc2MzF9.c-rfYIqw-jXZL9834jtusjtSpQq5yeHWXZ_73aQdxX4
Content-Type: application/json

{
    "password": "123456"
}

###
# delete users
DELETE  http://localhost:3000/users/6032273fbc2c56019096b219 HTTP/1.1

###
# delete project from users
DELETE  http://localhost:3000/users/project/60321601a0356b0924c94bde HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDMyMjcxZGJjMmM1NjAxOTA5NmIyMTciLCJpYXQiOjE2MTM5MDc2MzF9.c-rfYIqw-jXZL9834jtusjtSpQq5yeHWXZ_73aQdxX4

###
# ____________________________ PROJECTS ____________________________

# GET SPECIFIC PROJECT FROM TEAM
GET http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60321a53a20b560b1ec1591f HTTP/1.1 

###
# CREATE NEW PROJECT IN TEAM
POST http://localhost:3000/teams/602daad612d3182dc04f8050/projects HTTP/1.1
content-type: application/json

{
    "projectName": "nowy testowy projekt",
    "owner": {
        "id": "602e41a034644bbf940bea0b",
        "name": "Michauuu"
    }
}

###

###

# UPDATE MEMBERS IN PROJECT
PUT http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60322dad45e83a100382c5a3/members HTTP/1.1
content-type: application/json

{
    "member": {"id": "60324aea104714127c8f418b", "role": "Designer", "name": "asda"},
    "delete": true
}

###

# UPDATE PROJECT STATUS
PUT http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60321a53a20b560b1ec1591f/status HTTP/1.1
content-type: application/json

{
    "status": "Done"
}


###

# UPDATE PROJECT INFO
PUT http://localhost:3000/teams/602daad612d3182dc04f8050/projects/603215b9a0356b0924c94bdc/info HTTP/1.1
content-type: application/json

{
    "projectName": "Changed name",
    "content": "added content"
}

###

# DELETE PROJECT 
DELETE http://localhost:3000/teams/602daad612d3182dc04f8050/projects/603215b9a0356b0924c94bdc HTTP/1.1


#################################### NOTES ##############################################

# GET ALL NOTES FROM PROJECT
GET http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60321601a0356b0924c94bde/notes HTTP/1.1

###

# CREATE NEW NOTE
POST http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60321a53a20b560b1ec1591f/notes HTTP/1.1
Content-Type: application/json

{
    "name": "Test Note",
    "author": {"name": "Michal", "id": "602e41a034644bbf940bea0b"}
}

###

# UPDATE NOTE
PUT http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60321601a0356b0924c94bde/notes/6032160da0356b0924c94bdf HTTP/1.1
Content-Type: application/json

{
    "content": "updated contentasdwegsdgfg"
}

###


# DELETE NOTE
DELETE http://localhost:3000/teams/602daad612d3182dc04f8050/projects/60321a53a20b560b1ec1591f/notes/6032cab3c9b9c91bc1408a5d HTTP/1.1

############################## TASKS ######################################

# CREATE NEW TASK IN PROJECT
POST http://localhost:3000/teams/6033a1b028500c3c309e919e/projects/60320e1348b544024a5dbfa2/tasks HTTP/1.1
content-type: application/json

{
    "name": "TestTask",
    "content": "TestContent",
    "deadlineDate": "12/12/2001"
}

###

# DELETE TASK

DELETE http://localhost:3000/teams/6033a1b028500c3c309e919e/projects/60320e1348b544024a5dbfa2/tasks/6033c3271a688a07c41cc1da HTTP/1.1

#